[package]
name = "eldoria_quest"
version = "0.4.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
noise = "0.9.0"
